name: trace_foodchain_app
description: Trace Foodchains App for the diasca project

publish_to: 'none'

version: 1.2.5+14

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  http: ^1.2.1
  qr_flutter: ^4.0.0
  # qr_code_scanner: ^1.0.1
  mobile_scanner: ^6.0.2
  flutter_nfc_kit: ^3.3.1
  geolocator: ^13.0.1
  camera: ^0.11.0+1
  intl: any
  connectivity_plus: ^6.0.3
  path_provider: ^2.0.15
  nfc_manager: ^3.5.0
  hive_flutter: ^1.1.0
  hive: ^2.0.0
  fl_chart: ^0.69.0
  mockito: ^5.4.4
  workmanager: ^0.5.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  flutter_speed_dial: ^7.0.0
  pdf: ^3.8.0
  printing: ^5.9.0
  device_info_plus: ^10.1.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.7.0
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^5.4.5
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^17.2.3
  flutter_dotenv: ^5.1.0
  device_preview: ^1.2.0
  # encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  json_path: ^0.7.5
  share_plus: ^10.1.4
  auto_size_text: ^3.0.0
  excel: ^2.1.0


  # flutter_test: any
  # path: any
  # flutter_gen: any
  # crypto: any
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.1.7
  hive_generator: ^2.0.1
  json_serializable: ^6.1.4
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/flags/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/favicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/favicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/favicon.png"
